# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - name: Send mailer
      if: ${{ failure() }}
      uses: devellany/send-mail@v1.0.2
      with:
        # Enter SMTP host.
        host: smtp.gmail.com
        # Enter SMTP port. (defaults to 465)
        port: 465
        # Enter SMTP host account.
        account: ${{ secrets.GMAIL_ACCOUNT }}
        # Enter SMTP host account password.
        password: ${{ secrets.GMAIL_PASSWORD}}
        # Enter sender name.
        sender: Github Actions
        # Enter sender mail.
        from: ${{ secrets.GMAIL_ACCOUNT }}
        # Enter recipient emails and separated with 'comma'. (The prefix 'file://' if you want to read a file)
        to: ttanuj09@gmail.com
        # Enter the subject of the mail. (The prefix 'file://' if you want to read a file)
        subject: Hello
        # Enter the body of the mail. (The prefix 'file://' if you want to read a file)
        body: Yellow
        # Enter Content-Type HTTP header. (defaults to 'text/plain')
        contentType: text/plain
        attachments: '[{}]'
