name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]


    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
      env: 
        CI: true
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/wavss:latest
        
    - name: Send mailer
      if: ${{ failure() }}
      uses: devellany/send-mail@v1.0.2
      with:
        host: smtp.gmail.com
        port: 465
        account: ${{ secrets.GMAIL_ACCOUNT }}
        password: ${{ secrets.GMAIL_PASSWORD}}
        sender: Github Actions
        from: ${{ secrets.GMAIL_ACCOUNT }}
        to: tanuj.pandey18@st.niituniversity.in, anup.mishra18@st.niituniversity.in, titas.das18@st.niituniversity.in
        subject: Build Failure
        body: An Error ocurred in the job. Please visit https://github.com/pandeyjiseeti/WAVSS/actions.
        contentType: text/plain
        attachments: '[{}]'
